import { test, expect } from '@playwright/test';
import { createBackend, graphPayload } from './gas-harness.mjs';
import { COLLECTION_SEGMENTS } from '../src/workflow/segments.js';

async function setup(page) {
  const backend = createBackend({ bypassAuth: false });
  const admin = backend.request('login', { correo: 'admin@example.test', password: 'test-password' }).data;
  const request = (action, data = {}) => backend.request(action, { ...data, sessionToken: admin.sessionToken });
  request('saveReader', { password: 'test-password', correo: 'reader@example.test', nombre: 'Lector' });
  const folder = request('saveFolder', { nombre: 'Cliente principal' }).data;
  const team = request('createTeam', { nombre: 'Cobranza', carpetaId: folder.id, etiqueta: '#Cobranza' }).data;
  const process = request('createProcess', { nombre: 'Negociación de deuda', teamId: team.id }).data;
  const payload = graphPayload(team, process);
  payload.flow.nombre = 'Playbook de cobranza'; payload.flow.segmentos = structuredClone(COLLECTION_SEGMENTS);
  payload.nodes.forEach((n, i) => { n.metadata = { segmentId: i < 2 ? 'presentacion' : 'registro', editorPosition: { x: i * 400, y: i * 240 } }; });
  const graph = request('saveFullFlow', payload).data;
  await page.route('https://script.google.com/**', async route => {
    const req = route.request(), { action, ...data } = req.method() === 'POST' ? req.postDataJSON() : Object.fromEntries(new URL(req.url()).searchParams);
    await route.fulfill({ json: backend.request(action, data, req.method()) });
  });
  return { backend, request, graph, team, folder };
}
async function login(page, role) {
  await page.getByLabel('Correo', { exact: true }).fill(role + '@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('test-password');
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByText('Biblioteca de flujos', { exact: true })).toBeVisible();
}
test('login y creación/restablecimiento de lectores usan solo Code.gs', async ({ page }) => {
  await setup(page);
  const external = [];
  page.on('request', req => { if (['fetch', 'xhr'].includes(req.resourceType()) && req.url().startsWith('https://') && !req.url().startsWith('https://script.google.com/')) external.push(req.url()); });
  await page.goto('/');
  await page.getByLabel('Correo', { exact: true }).fill('admin@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('wrong-password');
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Credenciales incorrectas');
  await login(page, 'admin');
  await page.getByRole('button', { name: 'Usuarios', exact: true }).click();
  await page.getByLabel('Nombre', { exact: true }).fill('Nuevo lector');
  await page.getByLabel('Correo', { exact: true }).fill('nuevo@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('contraseña-inicial-segura');
  await page.getByRole('button', { name: 'Guardar lector', exact: true }).click();
  const row = page.getByRole('row').filter({ hasText: 'nuevo@example.test' });
  await expect(row).toContainText('Nuevo lector');
  await row.getByRole('button', { name: 'Editar lector' }).click();
  await page.getByLabel('Contraseña', { exact: true }).fill('contraseña-nueva-segura');
  await page.getByRole('button', { name: 'Guardar lector', exact: true }).click();
  await expect(page.getByLabel('Contraseña', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
  await expect(page.getByRole('button', { name: 'Iniciar sesión', exact: true })).toBeVisible();
  await page.getByLabel('Correo', { exact: true }).fill('nuevo@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('contraseña-nueva-segura');
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByText('Biblioteca de flujos', { exact: true })).toBeVisible();
  await expect(page.getByText('Solo lectura', { exact: false })).toBeVisible();
  expect(external).toEqual([]);
});
test('login lector permite consultar toda la biblioteca y navegar sin herramientas de escritura', async ({ page }) => {
  const { graph, team } = await setup(page);
  await page.goto('/'); await login(page, 'reader');
  await expect(page.getByText('Solo lectura', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: '+ Nuevo flujo', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '+ Nueva carpeta', exact: true })).toHaveCount(0);
  await page.getByLabel('Filtrar por carpeta').selectOption({ label: 'Cliente principal' });
  await page.getByRole('button', { name: 'Abrir mapa de Playbook de cobranza' }).click();
  await expect(page.getByLabel('Segmentos del flujo')).toContainText('Negociación');
  await expect(page.getByRole('button', { name: 'Editar flujo', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '▶ Recorrer', exact: true }).click();
  await expect(page.getByLabel('Detalle del nodo')).toContainText('Titularidad');
  await page.goto('/equipos/' + team.id);
  await expect(page.getByRole('button', { name: '+ Proceso', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /Eliminar/ })).toHaveCount(0);
  await page.goto('/usuarios'); await expect(page).toHaveURL(/\/$/);
  await page.goto('/flujos/' + graph.flow.id); await page.reload();
  await expect(page.getByRole('button', { name: '▶ Recorrer', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Iniciar sesión', exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByRole('button', { name: 'Iniciar sesión', exact: true })).toBeVisible();
});
test('administrador edita segmento, revisión y mejora; el color y los IDs persisten', async ({ page }) => {
  await page.setViewportSize({ width: 1500, height: 1000 });
  const { graph, request } = await setup(page);
  await page.goto('/'); await login(page, 'admin');
  await page.goto('/flujos/' + graph.flow.id);
  await page.getByRole('button', { name: 'Editar flujo', exact: true }).click();
  await page.getByLabel('Segmento del nodo', { exact: true }).selectOption('registro');
  await page.getByLabel('Revisión del criterio documental', { exact: true }).selectOption('no_aplica');
  await page.getByLabel('Justificación de calidad', { exact: true }).fill('Cliente terminó la interacción');
  await page.getByLabel('Error u oportunidad de mejora y optimización propuesta').fill('Precisar el criterio de tipificación');
  const segment = page.locator('.wf-inspector details[data-segment-id="registro"]');
  await segment.locator('summary').click();
  await segment.getByLabel('Nombre', { exact: true }).fill('Registro consistente');
  await segment.getByLabel('Color', { exact: true }).fill('#a21caf');
  await page.getByRole('button', { name: 'Guardar avance', exact: true }).click();
  await expect(page.locator('.wf-message')).toContainText('Avance guardado');
  const saved = request('getFullFlow', { flowId: graph.flow.id }).data;
  expect(saved.nodes[0].id).toBe(graph.nodes[0].id);
  expect(saved.nodes[0].metadata.calidad.estado).toBe('no_aplica');
  expect(saved.flow.segmentos.find(s => s.id === 'registro').color).toBe('#a21caf');
  await page.getByRole('button', { name: 'Cerrar constructor', exact: true }).click();
  await page.reload();
  await expect(page.getByLabel('Segmentos del flujo')).toContainText('Registro consistente');
  await expect(page.locator('.diagram-node[data-segment="registro"]').first()).toHaveCSS('--segment-color', '#a21caf');
  await page.goto('/flujos/' + graph.flow.id + '?nodo=' + graph.nodes[0].id);
  await expect(page.getByLabel('Detalle del nodo')).toContainText('Precisar el criterio de tipificación');
  await page.screenshot({ path: 'test-results/segments-admin.png', fullPage: true });
});

test('administrador organiza carpetas y desactiva lectores desde la interfaz', async ({ page }) => {
  const { request, team, graph } = await setup(page);
  await page.goto('/'); await login(page, 'admin');
  await page.getByRole('button', { name: '+ Nueva carpeta', exact: true }).click();
  await page.locator('.folder-form').getByLabel('Nombre', { exact: true }).fill('Operación regional');
  await page.locator('.folder-form').getByLabel('Descripción', { exact: true }).fill('Equipo de cobranza regional');
  await page.getByRole('button', { name: 'Guardar carpeta', exact: true }).click();
  await expect(page.locator('.folder-form')).toHaveCount(0);
  const folder = request('getFolders').data.find(f => f.nombre === 'Operación regional');
  await page.goto('/equipos');
  await page.getByRole('button', { name: 'Editar equipo Cobranza', exact: true }).click();
  await page.getByRole('combobox', { name: 'Carpeta / grupo principal' }).selectOption(folder.id);
  await page.getByRole('button', { name: 'Guardar equipo', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect(request('getTeams').data.find(t => t.id === team.id).carpetaId).toBe(folder.id);
  await page.goto('/');
  await page.getByLabel('Filtrar por carpeta').selectOption(folder.id);
  await expect(page.getByRole('button', { name: graph.flow.nombre, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Usuarios', exact: true }).click();
  await page.getByRole('button', { name: 'Editar lector', exact: true }).click();
  await page.getByLabel('Acceso activo', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Guardar lector', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'reader@example.test' })).toContainText('Desactivado');
  expect(request('getUsers').data.find(u => u.correo === 'reader@example.test').activo).toBe(false);
});
