import { test, expect } from '@playwright/test';
import { createBackend, seedHierarchy, graphPayload } from './gas-harness.mjs';
import { mockBackend, addNode, connect } from './editor-helpers.mjs';

test('decisiones automáticas, área ampliada, descripciones flotantes y comentarios persistentes', async ({ page }) => {
  await page.setViewportSize({width:1500,height:1000});
  const backend=createBackend(),{team}=seedHierarchy(backend);
  await mockBackend(page,backend); await page.goto('/equipos/'+team.id);
  await page.getByRole('button',{name:'+ Flujo',exact:true}).click();
  await page.getByLabel('Nombre del flujo',{exact:true}).fill('Decisiones y comentarios');
  await page.getByLabel('Descripción del nodo',{exact:true}).fill('Documentación en https://example.com/guia');
  await expect(page.locator('.diagram-copy')).not.toContainText('Documentación');
  const start=page.locator('.diagram-node').filter({hasText:'Inicio'});
  await expect(page.getByRole('tooltip')).not.toBeVisible();
  await start.hover(); await expect(page.getByRole('tooltip')).toContainText('Documentación');
  expect(await page.getByRole('tooltip').evaluate(e => { const r=e.getBoundingClientRect(); return r.x >= 0 && r.y >= 0 && r.right <= innerWidth && r.bottom <= innerHeight; })).toBe(true);
  const url=start.getByRole('link',{name:'Abrir enlace 1 de Inicio'});
  await expect(url).toHaveAttribute('href','https://example.com/guia'); await expect(url).toHaveAttribute('target','_blank');
  expect(await start.locator('.react-flow__handle').first().evaluate(e=>e.offsetWidth)).toBeGreaterThanOrEqual(20);
  await addNode(page,'Decisión','Decidir');
  for(const name of ['A','B','C']) await addNode(page,'Actividad',name);
  await connect(page,'Inicio','Decidir');
  await connect(page,'Decidir','A','Izquierdo','Derecho');
  await connect(page,'Decidir','B','Derecho','Izquierdo');
  await expect(page.locator('.react-flow__edge').filter({hasText:'Sí'})).toHaveCount(1);
  await expect(page.locator('.react-flow__edge').filter({hasText:'No'})).toHaveCount(1);
  await connect(page,'Decidir','C','Inferior');
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('dos salidas');
  await expect(page.locator('.react-flow__edge')).toHaveCount(3);
  await page.getByRole('button',{name:'Texto flotante',exact:true}).click();
  await page.getByLabel('Texto del comentario').fill('Responsable: equipo de soporte');
  await expect(page.locator('[data-shape="text"] .react-flow__handle')).toHaveCount(0);
  await page.getByRole('button',{name:'Guardar flujo',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const saved=backend.request('getAllFlows').data[0];
  const graph=backend.request('getFullFlow',{flowId:saved.id}).data;
  const comment=graph.nodes.find(n=>n.metadata.kind==='annotation');
  expect(comment.titulo).toBe('Responsable: equipo de soporte');expect(comment.flowId).toBe(saved.id);
  expect(graph.edges.map(e=>e.condicion)).toEqual(['siempre','positivo','negativo']);
  await page.reload(); await expect(page.locator('[data-shape="text"]')).toContainText('Responsable: equipo de soporte');
  await page.getByRole('button',{name:'Editar flujo',exact:true}).click();
  await page.getByRole('button',{name:'Ver todo',exact:true}).last().click();
  const annotation=page.getByRole('dialog').locator('.react-flow__node').filter({hasText:'Responsable: equipo de soporte'});
  await annotation.click(); await page.getByLabel('Texto del comentario').fill('Comentario actualizado');
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const edited=backend.request('getFullFlow',{flowId:saved.id}).data.nodes.find(n=>n.id===comment.id);
  expect(edited.titulo).toBe('Comentario actualizado'); expect(edited.metadata.editorPosition).toEqual(comment.metadata.editorPosition);
});

test('estados, vínculos entre flujos, volver al elemento y mapa por equipo', async ({ page }) => {
  await page.setViewportSize({width:1500,height:1000});
  const backend=createBackend(),{team,process}=seedHierarchy(backend);
  const targetPayload=graphPayload(team,process); targetPayload.flow.nombre='Flujo destino';
  const target=backend.request('saveFullFlow',targetPayload).data.flow;
  const otherTeam=backend.request('createTeam',{nombre:'Otro equipo'}).data;
  const otherProcess=backend.request('createProcess',{teamId:otherTeam.id,nombre:'Otro proceso'}).data;
  backend.request('saveFullFlow',graphPayload(otherTeam,otherProcess));
  await mockBackend(page,backend);await page.goto('/equipos/'+team.id);
  await page.getByRole('button',{name:'+ Flujo',exact:true}).click();
  await page.getByLabel('Nombre del flujo',{exact:true}).fill('Flujo origen');
  const status=page.getByLabel('Estado del flujo');
  expect(await status.locator('option').allTextContents()).toEqual(['Borrador','Activo','Validación','Desactivado']);
  await status.selectOption('validacion');
  await page.getByLabel('Flujo vinculado',{exact:true}).selectOption(target.id);
  await page.getByRole('button',{name:'Guardar flujo',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const source=backend.request('getAllFlows').data.find(f=>f.nombre==='Flujo origen');
  expect(source.estado).toBe('validacion');
  await page.getByRole('link',{name:'Continuar al flujo vinculado desde Inicio',exact:true}).click();
  await expect(page).toHaveURL(new RegExp('/flujos/'+target.id+'$'));
  await page.getByRole('button',{name:'← Volver',exact:true}).click();
  await expect(page).toHaveURL(new RegExp('/flujos/'+source.id+'\\?nodo='));
  await expect(page.getByLabel('Detalle del nodo')).toContainText('Inicio');
  for(const state of ['activo','desactivado','borrador']) {
    await page.getByRole('button',{name:'Editar flujo',exact:true}).click();
    await page.getByLabel('Estado del flujo').selectOption(state);
    await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    expect(backend.request('getAllFlows').data.find(f=>f.id===source.id).estado).toBe(state);
  }
  await page.getByRole('link',{name:'Vista general',exact:true}).click();
  await expect(page.locator('.overview-status')).toHaveText('2 flujos · 1 vínculos dentro del equipo');
  await expect(page.locator('.react-flow__node')).toHaveCount(2);
  await expect(page.locator('.react-flow__edge')).toHaveCount(1);
  await page.getByLabel('Equipo del mapa').selectOption(otherTeam.id);
  await expect(page.locator('.overview-status')).toHaveText('1 flujos · 0 vínculos dentro del equipo');
  await expect(page.locator('.react-flow__node')).toHaveCount(1);
  await page.reload(); await expect(page.getByLabel('Equipo del mapa')).toHaveValue(otherTeam.id);
});
