import { test, expect } from '@playwright/test';
import { createBackend, seedHierarchy } from './gas-harness.mjs';
import { mockBackend, addNode, connect } from './editor-helpers.mjs';

test('puntos reaccionan suavemente al cursor sin ondas, bloqueos ni movimiento continuo', async ({ page }) => {
  await page.setViewportSize({ width: 1400, height: 900 });
  await page.goto('/');
  const background = page.locator('.app-point-shell > .point-background');
  const canvas = background.locator('canvas');
  await expect(background).toHaveAttribute('data-motion', 'interactive');
  await expect(background).toHaveCSS('pointer-events', 'none');
  await expect(canvas).toHaveCount(1);
  await expect.poll(() => canvas.evaluate(el => el.width)).toBeGreaterThan(100);
  const checksum = () => canvas.evaluate(el => {
    const data = el.getContext('2d').getImageData(64, 64, 64, 64).data;
    let hash = 2166136261;
    for (const byte of data) hash = Math.imul(hash ^ byte, 16777619);
    return hash >>> 0;
  });
  const initial = await checksum();
  await page.mouse.move(90, 90);
  await expect(background).toHaveAttribute('data-state', 'reacting');
  expect(await checksum()).not.toBe(initial);
  await page.mouse.click(90, 90);
  await expect(background).toHaveAttribute('data-state', 'idle');
  expect(await checksum()).toBe(initial);
  expect(await background.evaluate(el => el.getAnimations({ subtree: true }).length)).toBe(0);
  await page.getByLabel('Correo', { exact: true }).fill('lector@example.test');
  await expect(page.getByLabel('Correo', { exact: true })).toHaveValue('lector@example.test');
  await page.screenshot({ path: 'test-results/point-login.png', fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(background).toHaveAttribute('data-motion', 'reduced');
  await page.mouse.move(90, 90);
  await expect(background).toHaveAttribute('data-state', 'idle');
  expect(await checksum()).toBe(initial);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('canvas con puntos conserva paneo, conexiones, guardado y mapa de lectura', async ({ page }) => {
  await page.setViewportSize({ width: 1500, height: 1000 });
  const backend = createBackend(), { team } = seedHierarchy(backend), errors = [];
  page.on('pageerror', error => { if (!error.message.includes('ResizeObserver loop')) errors.push(error.message); });
  await mockBackend(page, backend); await page.goto('/equipos/' + team.id);
  await page.getByRole('button', { name: '+ Flujo', exact: true }).click();
  await page.getByLabel('Nombre del flujo', { exact: true }).fill('Flujo con fondo puntos');
  await addNode(page, 'Actividad', 'Verificar deuda');
  await addNode(page, 'Fin', 'Cerrar gestión');
  await connect(page, 'Inicio', 'Verificar deuda');
  await connect(page, 'Verificar deuda', 'Cerrar gestión');
  const canvas = page.getByRole('dialog').getByLabel('Lienzo del editor');
  const background = canvas.locator(':scope > .point-background');
  await expect(background).toHaveAttribute('data-motion', 'interactive');
  await expect(canvas.locator('.react-flow__background')).toHaveCount(0);
  await expect(canvas.locator(':scope > .react-flow')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
  const bounds = await canvas.boundingBox(), viewport = canvas.locator('.react-flow__viewport');
  const previous = await viewport.getAttribute('style');
  await page.mouse.move(bounds.x + 70, bounds.y + 110);
  await page.mouse.down(); await page.mouse.move(bounds.x + 170, bounds.y + 190, { steps: 8 }); await page.mouse.up();
  await expect.poll(() => viewport.getAttribute('style')).not.toBe(previous);
  await page.getByRole('button', { name: 'Guardar flujo', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.wf-read-canvas > .point-background')).toHaveAttribute('data-motion', 'interactive');
  await expect(page.locator('.wf-read-canvas .react-flow__background')).toHaveCount(0);
  await page.getByRole('button', { name: '▶ Recorrer', exact: true }).click();
  await page.getByRole('button', { name: '→ Continuar', exact: true }).click();
  await expect(page.getByLabel('Detalle del nodo')).toContainText('Verificar deuda');
  const graph = backend.request('getFullFlow', { flowId: backend.request('getAllFlows').data[0].id }).data;
  expect(graph.nodes).toHaveLength(3); expect(graph.edges).toHaveLength(2);
  await page.getByRole('button', { name: 'Ver todo', exact: true }).click();
  await page.screenshot({ path: 'test-results/point-canvas.png', fullPage: true });
  await page.goto('/vista-general?equipo=' + team.id);
  await expect(page.locator('.overview-canvas > .point-background')).toHaveAttribute('data-motion', 'interactive');
  await expect(page.locator('.overview-canvas .react-flow__background')).toHaveCount(0);
  expect(errors).toEqual([]);
});
