import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { createBackend, seedHierarchy, graphPayload } from './gas-harness.mjs';
import { mockBackend, addNode, connect } from './editor-helpers.mjs';

test('editor visual: formas, decisión, split, ciclo, modelo, puertos; biblioteca y edición persistente', async ({ page }) => {
  await page.setViewportSize({ width: 1500, height: 1000 });
  const backend = createBackend(), { team } = seedHierarchy(backend), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await mockBackend(page, backend); await page.goto('/');
  await page.getByRole('button', { name: '+ Nuevo flujo', exact: true }).click();
  await page.getByRole('button', { name: 'Abrir constructor', exact: true }).click();
  await page.getByLabel('Nombre del flujo', { exact: true }).fill('Revisión de repositorios');
  await page.getByLabel('Título del nodo', { exact: true }).fill('Inicio');
  await addNode(page, 'Decisión', '¿Aprobado?');
  await page.getByLabel('Valor a evaluar').fill('{{repos.count}}');
  await page.getByLabel('Operador', { exact: true }).fill('mayor que');
  await page.getByLabel('Valor de comparación').fill('3');
  await addNode(page, 'Base de datos', 'Consultar historial');
  await page.getByLabel('Tabla o recurso').fill('Repositorios');
  await addNode(page, 'Inteligencia artificial', 'Resumir repositorios');
  await page.getByLabel('Instrucciones del modelo').fill('Resume los cambios recientes.');
  await page.getByRole('button', { name: '+ Parámetro', exact: true }).click();
  await page.getByLabel('Nombre 1', { exact: true }).fill('candidate_repo_count');
  await page.getByLabel('Valor 1', { exact: true }).fill('3');
  await addNode(page, 'Modelo de IA', 'Gemini');
  await page.getByLabel('Identificador del modelo').fill('modelo-ejemplo');
  await addNode(page, 'Notificación', 'Enviar informe');
  await page.getByLabel('Destinatarios').fill('equipo@example.com');
  await page.getByRole('button', { name: '+ Adjunto', exact: true }).click();
  await page.getByLabel('Archivo 1').fill('informe.html');
  await page.getByLabel('Valor 1', { exact: true }).fill('{{html}}');
  await page.getByRole('button', { name: 'Ver todo', exact: true }).click();
  await page.getByRole('button', { name: 'Añadir entrada a Enviar informe', exact: true }).click();
  await page.getByRole('button', { name: 'Añadir salida a Enviar informe', exact: true }).click();
  await connect(page, 'Inicio', '¿Aprobado?');
  await connect(page, '¿Aprobado?', 'Resumir repositorios', 'Sí');
  await connect(page, '¿Aprobado?', 'Consultar historial', 'No');
  await connect(page, 'Consultar historial', '¿Aprobado?');
  await connect(page, 'Resumir repositorios', 'Enviar informe');
  await connect(page, 'Resumir repositorios', 'Consultar historial');
  await connect(page, 'Gemini', 'Resumir repositorios', 'Modelo', 'Modelo IA');
  await connect(page, 'Consultar historial', 'Enviar informe', 'Salida', 'Entrada 2');
  await page.getByRole('button', { name: 'Ordenar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver todo', exact: true }).click();
  await page.getByRole('button', { name: 'Ocultar mensaje' }).click();
  await expect.poll(() => page.locator('.wf-canvas').evaluate(el => {
    const box = el.getBoundingClientRect();
    return [...el.querySelectorAll('.react-flow__node')].every(n => { const r = n.getBoundingClientRect(); return r.left >= box.left && r.right <= box.right && r.top >= box.top && r.bottom <= box.bottom; });
  })).toBe(true);
  await expect(page.locator('.wf-shape-diamond')).toHaveCount(1);
  await expect(page.locator('.wf-shape-cylinder')).toHaveCount(1);
  await expect(page.locator('.react-flow__edge-path[style*="stroke-dasharray"]')).toHaveCount(1);
  mkdirSync('docs/validation', { recursive: true });
  await page.screenshot({ path: 'docs/validation/editor-visual-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Guardar flujo', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByText('Recién guardado', { exact: true })).toBeVisible();
  await expect(page.getByRole('table')).toBeVisible();
  await page.screenshot({ path: 'docs/validation/biblioteca-desktop.png', fullPage: true });
  const saved = backend.request('getAllFlows').data[0];
  const graph = backend.request('getFullFlow', { flowId: saved.id }).data;
  expect(graph.edges).toHaveLength(8);
  expect(graph.edges.filter(e => e.tipo === 'modelo')).toHaveLength(1);
  const email = graph.nodes.find(n => n.tipo === 'notificacion');
  expect(email.metadata.ports.inputs).toHaveLength(2);
  expect(email.metadata.ports.outputs).toHaveLength(2);
  expect(email.metadata.attachments[0].name).toBe('informe.html');
  await page.getByRole('button', { name: 'Abrir mapa de Revisión de repositorios' }).click();
  await expect(page.getByLabel('Mapa navegable del flujo')).toBeVisible();
  await expect(page.locator('canvas')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Vista 3D', exact: true })).toHaveCount(0);
  expect(await page.locator('.wf-read-canvas').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(255, 255, 255)');
  await page.getByRole('button', { name: '▶ Recorrer', exact: true }).click();
  await page.getByRole('button', { name: '→ Continuar', exact: true }).click();
  await expect(page.getByText('Evalúa la condición y elige Sí o No.')).toBeVisible();
  await page.getByRole('button', { name: '✗ No', exact: true }).click();
  await expect(page.getByText('Consultar historial', { exact: true }).last()).toBeVisible();
  await page.getByRole('button', { name: '→ ¿Aprobado?', exact: true }).click();
  await page.getByRole('button', { name: '✓ Sí', exact: true }).click();
  await expect(page.getByRole('button', { name: /→ Gemini/ })).toHaveCount(0);
  await expect.poll(() => page.locator('.wf-node.is-selected').evaluate(el => {
    const node = el.getBoundingClientRect(), area = el.closest('.wf-canvas').getBoundingClientRect();
    return Math.round(node.x + node.width / 2 - area.x - area.width / 2);
  })).toBe(0);
  await page.screenshot({ path: 'docs/validation/mapa-visual-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Editar flujo', exact: true }).click();
  await page.getByLabel('Nombre del flujo', { exact: true }).fill('Revisión actualizada');
  await page.getByLabel('Título del nodo', { exact: true }).fill('Inicio actualizado');
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await expect(page.getByText('Revisión actualizada', { exact: true })).toBeVisible();
  expect(backend.request('getAllFlows').data).toHaveLength(1);
  const edited = backend.request('getFullFlow', { flowId: saved.id }).data;
  expect(edited.nodes.find(n => n.id === graph.nodes[0].id).titulo).toBe('Inicio actualizado');
  await page.getByRole('button', { name: '← Biblioteca', exact: true }).click();
  await expect(page.getByLabel('Filtrar por equipo')).toHaveValue(team.id);
  await expect(page.getByRole('button', { name: 'Abrir mapa de Revisión actualizada' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('biblioteca filtra por equipo y proceso y conserva la jerarquía al recargar', async ({ page }) => {
  const backend = createBackend(), { team, process } = seedHierarchy(backend);
  backend.request('saveFullFlow', graphPayload(team, process));
  const other = backend.request('createProcess', { teamId: team.id, nombre: 'Proceso B' }).data;
  const second = graphPayload(team, other); second.flow.nombre = 'Flujo B'; backend.request('saveFullFlow', second);
  await mockBackend(page, backend); await page.goto('/');
  await page.getByLabel('Filtrar por proceso').selectOption(other.id);
  await expect(page.getByRole('button', { name: 'Flujo B', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Resolver ticket', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByLabel('Filtrar por proceso')).toHaveValue(other.id);
});

test('fallo de guardado y backend antiguo conservan el diseño en el editor', async ({ page }) => {
  const backend = createBackend(), { team } = seedHierarchy(backend);
  let old = true;
  await mockBackend(page, backend, action => action === 'getSchemaStatus' && old ? { success: true, data: { version: '1.1.0', requiereMigracion: false } } : null);
  await page.goto('/equipos/' + team.id);
  await page.getByRole('button', { name: '+ Flujo', exact: true }).click();
  await page.getByLabel('Nombre del flujo', { exact: true }).fill('Conservar borrador');
  await page.getByRole('button', { name: 'Guardar flujo', exact: true }).click();
  await expect(page.getByText(/Actualiza Code.gs a la versión 1.2.0/)).toBeVisible();
  expect(backend.request('getAllFlows').data).toHaveLength(0);
  old = false; backend.failNextWrite('nodos');
  await page.getByRole('button', { name: 'Guardar flujo', exact: true }).click();
  await expect(page.getByText('Fallo de escritura simulado', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Nombre del flujo', { exact: true })).toHaveValue('Conservar borrador');
  await page.getByRole('button', { name: 'Guardar flujo', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('constructor y biblioteca móviles no desbordan; cambia entre paneles y lienzo', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const backend = createBackend(), { team, process } = seedHierarchy(backend);
  backend.request('saveFullFlow', graphPayload(team, process));
  await mockBackend(page, backend); await page.goto('/');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'docs/validation/biblioteca-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '+ Nuevo flujo', exact: true }).click();
  await page.getByRole('button', { name: 'Abrir constructor', exact: true }).click();
  await addNode(page, 'Decisión', 'Decidir');
  await page.getByRole('button', { name: 'Lienzo', exact: true }).click();
  await page.getByRole('button', { name: 'Ver todo', exact: true }).click();
  await expect(page.locator('.wf-canvas')).toBeVisible();
  await page.screenshot({ path: 'docs/validation/editor-visual-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.keyboard.press('Escape');
  await expect(page.getByText('Hay cambios sin guardar.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Seguir editando' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar constructor', exact: true }).click();
  await page.getByRole('button', { name: 'Descartar y cerrar', exact: true }).click();
  await page.getByRole('button', { name: 'Abrir mapa de Resolver ticket' }).click();
  await page.getByRole('button', { name: '▶ Recorrer', exact: true }).click();
  await expect(page.getByRole('button', { name: '→ Continuar', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByLabel('Detalle del nodo', { exact: true })).toHaveCSS('opacity', '1');
  await page.screenshot({ path: 'docs/validation/mapa-visual-mobile.png', fullPage: true });
});

test('arrastrar desde paleta, conectar puertos, mover nodo y desplazar el lienzo 2D', async ({ page }) => {
  await page.setViewportSize({ width: 1400, height: 950 });
  const backend = createBackend(), { team } = seedHierarchy(backend);
  await mockBackend(page, backend); await page.goto('/equipos/' + team.id);
  await page.getByRole('button', { name: '+ Flujo', exact: true }).click();
  await page.getByLabel('Nombre del flujo', { exact: true }).fill('Arrastre 2D');
  const canvas = page.locator('.wf-canvas');
  await page.getByRole('button', { name: 'Añadir Paso', exact: true }).dragTo(canvas, { targetPosition: { x: 380, y: 470 } });
  await expect(page.locator('.react-flow__node')).toHaveCount(2);
  await page.getByLabel('Título del nodo', { exact: true }).fill('Revisar');
  await page.getByRole('button', { name: 'Ordenar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver todo', exact: true }).click();
  const start = page.locator('.react-flow__node').filter({ hasText: 'Schedule Trigger' });
  const end = page.locator('.react-flow__node').filter({ hasText: 'Revisar' });
  const source = start.locator('.react-flow__handle[data-handleid="out"]');
  const target = end.locator('.react-flow__handle[data-handleid="in"]');
  await expect(source).toBeVisible(); await expect(target).toBeVisible();
  // Espera a que termine el encuadre antes de arrastrar coordenadas de pantalla.
  await expect.poll(async () => { const a = await source.boundingBox(); await page.waitForTimeout(60); const b = await source.boundingBox(); return Math.abs(a.x - b.x) + Math.abs(a.y - b.y) < .1; }).toBe(true);
  const a = await source.boundingBox(), b = await target.boundingBox();
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2); await page.mouse.down();
  await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps: 15 }); await page.mouse.up();
  await expect(page.locator('.react-flow__edge')).toHaveCount(1);
  const before = await end.getAttribute('style'), rect = await end.boundingBox();
  await page.mouse.move(rect.x + 60, rect.y + 60); await page.mouse.down(); await page.mouse.move(rect.x + 100, rect.y + 150, { steps: 12 }); await page.mouse.up();
  await expect(end).not.toHaveAttribute('style', before);
  const viewport = page.locator('.react-flow__viewport'), previous = await viewport.getAttribute('style'), pane = await canvas.boundingBox();
  await page.mouse.move(pane.x + 50, pane.y + 100); await page.mouse.down(); await page.mouse.move(pane.x + 110, pane.y + 130, { steps: 10 }); await page.mouse.up();
  await expect(viewport).not.toHaveAttribute('style', previous);
  await page.getByRole('button', { name: 'Guardar flujo', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const graph = backend.request('getFullFlow', { flowId: backend.request('getAllFlows').data[0].id }).data;
  expect(graph.nodes.find(n => n.titulo === 'Revisar').metadata.editorPosition.y).toBeGreaterThan(0);
  await page.reload(); await expect(page.locator('.react-flow__edge')).toHaveCount(1);
});
